### ISSUE TITLE
Inject custom validation logic

### ISSUE THREAD

**Issue by slinkydeveloper** [everit-org/json-schema#122]
Hi,
There is a way to inject a custom validation logic when i build the schema? I'm trying to use this library to validate datas across oas 3 schemas, not json schemas (in fact they are really similar they differ only for some things). I want to add the support for polymorphism as explained here with discriminator https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

You have any ideas?

**Comment by erosb** [comment]
Hello Francesco,

I'm not sure if I understand your use case. I read (well, quickly) the
article you linked, and it seems to me the discriminator property is
necessary only when you want to map the json content to domain objects. I
don't see how can it affect validation. I can understand how it is needed
by openapi for scenarios other than validation though.

Also, the discriminator property looks to be adjacent to the schema
property, not a child of it, so again it confuses me.

Could you please provide a bit more context about what you are trying to
achieve?

Thanks,


2017.12.01. 9:13 ezt írta ("Francesco Guardiani" <notifications@github.com

**Comment by slinkydeveloper** [comment]
The fact is that I want to inject custom logic for:
- default (as is now is not supported)
- nullable
- readOnly/writeOnly (maybe I can solve that thing preprocessing the schema)
- discriminator

As you can see, in this article there are the differences between oas schemas and json schemas: https://swagger.io/docs/specification/data-models/keywords/

The discriminator applies when you want to use `oneOf` or `anyOf`. Basically inside the json you send during the request you add a field (the `discriminator`) that explain what type (one of the schemas of `anyOf`/`oneOf`) are you sending, so the validator have to validate the json only to one of the schemas described. For example:
```yaml
oneOf:
  - type: object
    name: objectWithNumbers
    additionalProperties: false
    properties:
      objectType:
        type: string
      a:
        type: number
  - type: object
    name: objectWithString
    additionalProperties: true
    properties:
      objectType:
        type: string
      b:
        type: string
discriminator:
  propertyName: objectType
```

If you try to validate for example, in a scenario without the discriminator, this yaml:
```yaml
a: "hello"
```
The behaviour can be strange, because the first schema allows a number, the second schema allows additional properties. discriminator helps solving this problems. With discriminator:
```yaml
objectType: objectWithNumber
a: "hello"
```
With discriminator support, we are sure that this validation returns false

I want to use that validator inside [vert.x-web-api-contract](http://vertx.io/docs/vertx-web-api-contract/java/). In this library I validate HTTP requests across oas schemas.
