### ISSUE TITLE
Validation of children schemas

### ISSUE THREAD

**Issue by trein** [everit-org/json-schema#210]
### Background:
This might not be an issue with the lib, but I just wanted to be sure. I have defined a meta-schema based on draft-04. Let's call it `custom-meta-schema.yaml`.

Based off my `custom-meta-schema.yaml`, I created children schemas that represent some standard API definition for my internal needs. Let's call one of these schema API as `child-schema.yaml`.

Just to illustrate what I'm talking about, here are snippets of `custom-meta-schema.yaml` and `child-schema.yaml`:

`custom-meta-schema.yaml`:
```yaml
title: 'Custom Meta Schema'
type: object
required:
  - title
  - description
  - interface
  - api
properties:
  interface:
    type: object
    required:
      - id
      - version
      - versionMode
    properties:
      id:
        type: string
      version:
        type: integer
      versionMode:
        type: string
        enum:
          - final
          - draft
  api:
    type: object
definitions:
  Int8:
    type: integer
    minimum: -128
    maximum: 127
  Int16:
    type: integer
    minimum: -32768
    maximum: 32767
```

`child-schema.yaml`:
```yaml
---
title: 'Child API Definition'
description: 'Some cool description here.'
interface:
  id: 'ChildAPI'
  version: 1
  versionMode: 'draft'
api:
  input:
    $ref: '#/definitions/Int8'
```

### Question:
As you might have noticed, I defined some data types in `custom-meta-schema.yaml` that can be declared in `child-schema.yaml`. I've been facing some issues validating that with the lib. I've tried canonical and inline dereferencing (setting the [id](https://json-schema.org/understanding-json-schema/structuring.html) property of my schema) as well as modifying the `$ref` string to different formats, but no luck. Is there a way to do it?
